name: sqa
description: ""
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.20.1
  mapbox_maps_flutter: ^2.0.0
  geolocator: ^13.0.2
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  country_flags: ^3.2.0
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.0
  uuid: ^4.5.1
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.7
  url_launcher: ^6.3.1
  firebase_messaging: ^15.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/sqa_logo.jpeg
    - assets/images/sqa_logo_no_margin.jpeg
  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: FontAwesome
      fonts:
        - asset: assets/fonts/FontAwesomeIcon.ttf
