// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ4GnboFDvN1Mtww3BSIYA2PykCsKhNNk',
    appId: '1:651712574900:web:f0d789f52a976e5476eee1',
    messagingSenderId: '651712574900',
    projectId: 'sqa-app-rbrns',
    authDomain: 'sqa-app-rbrns.firebaseapp.com',
    storageBucket: 'sqa-app-rbrns.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmMXHCVwGJezlXoP35mC6R_Qww5SIXs_M',
    appId: '1:651712574900:android:872a4c3a4eb6773276eee1',
    messagingSenderId: '651712574900',
    projectId: 'sqa-app-rbrns',
    storageBucket: 'sqa-app-rbrns.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1gxWFDIaS4YKyjGZrZbvjF8OXA99qAd0',
    appId: '1:651712574900:ios:fb0920ba16566b3976eee1',
    messagingSenderId: '651712574900',
    projectId: 'sqa-app-rbrns',
    storageBucket: 'sqa-app-rbrns.firebasestorage.app',
    iosBundleId: 'com.rbrns.sqa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1gxWFDIaS4YKyjGZrZbvjF8OXA99qAd0',
    appId: '1:651712574900:ios:fb0920ba16566b3976eee1',
    messagingSenderId: '651712574900',
    projectId: 'sqa-app-rbrns',
    storageBucket: 'sqa-app-rbrns.firebasestorage.app',
    iosBundleId: 'com.rbrns.sqa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ4GnboFDvN1Mtww3BSIYA2PykCsKhNNk',
    appId: '1:651712574900:web:2b1db9e481faa81276eee1',
    messagingSenderId: '651712574900',
    projectId: 'sqa-app-rbrns',
    authDomain: 'sqa-app-rbrns.firebaseapp.com',
    storageBucket: 'sqa-app-rbrns.firebasestorage.app',
  );
}
